### PR TITLE
ignore props by default for toMatchElement()

### LINKED ISSUE #163: toMatchElement() does not behave like matchesElement()
I have a component that does something like this:

```js
componentDidMount() {
  this.refToTextarea.focus();
}
```

This test with enzyme-matchers fails:

```js
it('focuses the textarea', () => {
    const root = mountMyComponent();
    expect(root.find('.MyComponent-textarea'))
      .toMatchElement(document.activeElement);
});
```

I see:

```
    Expected actual value to match the expected value.
    Expected:
     <textarea />
    Actual:
     <textarea className="MyComponent-textarea" onInput={[Function]} name="review" value={[undefined]} placeholder="The placeholder text." />
```

With a vanilla Jest/enzyme assertion the test passes:

```js
it('focuses the textarea', () => {
    const root = mountMyComponent();
    expect(
      root.find('.AddonReview-textarea')
        .matchesElement(document.activeElement)
    ).toEqual(true);
});
```

Shouldn't these both behave the same?

I'm running tests in Node with mocha. Versions:
```
Node: v6.10.3
Jest: 21.0.2
enzyme-matchers: 3.8.3
jest-enzyme: 3.8.3
jest-environment-jsdom: 21.0.2
  └─ jsdom@9.12.0
```

### PR DESCRIPTION
**Pull request by finnigantime**
Fixes #163 `toMatchElement() does not behave like matchesElement()`.

### CODE REVIEW

**Comment by finnigantime** [comment]
@blainekasten What should I do about the CI failure (can't find module)? :)

**Comment by blainekasten** [comment]
@finnigantime I fixed CI. So you would need to rebase. I have mixed feelings about the object-options API but I can't really think of something else I like more. So let's go with it. Could you fix the flow to not be `any` but instead create a:

```js
type Options = {
  ignoreProps?: boolean,
};
```

**Comment by finnigantime** [comment]
@blainekasten Made the suggested updates and rebased :)

File: packages/enzyme-matchers/src/assertions/toMatchElement.js [hunk 1]
```diff
@@ -7,13 +7,14 @@
...
-import type { EnzymeObject, Matcher } from '../types';
+import type { EnzymeObject, Matcher, ToMatchElementOptions } from '../types';
 import isShallowWrapper from '../utils/isShallowWrapper';
 import single from '../utils/single';
 
 function toMatchElement(
   actualEnzymeWrapper: EnzymeObject,
-  reactInstance: Object
+  reactInstance: Object,
+  options: ToMatchElementOptions = { ignoreProps: true }
```
Comment (blainekasten) [inline packages/enzyme-matchers/src/assertions/toMatchElement.js]: It seems that setting this property might become a breaking change, right? I think that's fine. I just want to make sure I release it properly.

Comment (finnigantime) [reply packages/enzyme-matchers/src/assertions/toMatchElement.js]: It's a new 3rd param that always gets a default value if none is passed in. I guess if someone is currently calling this method with an unused third param and it's not of type object, then it could break. But that's just bad code IMO, not a breaking change.

Comment (finnigantime) [reply packages/enzyme-matchers/src/assertions/toMatchElement.js]: I can see that it *could* possibly break some cases but seems very unlikely.

Comment (blainekasten) [reply packages/enzyme-matchers/src/assertions/toMatchElement.js]: I forget what the previous code did. Before this change, was the behavior of `toMatchElement` that it ignored props?

Comment (finnigantime) [reply packages/enzyme-matchers/src/assertions/toMatchElement.js]: Ah - you are correct, it did not ignore props before, so this will be breaking. Thank you for catching this.

Comment (blainekasten) [reply packages/enzyme-matchers/src/assertions/toMatchElement.js]: Cool. No worries. Just wanted to make sure I understood. So this is fine. I feel like it's the right default. A new major is fine.
